package board.games.bunker.enums;

public enum DropInteraction {
    HOBBY,
    HEALTH,
    EXTRA_SKILLS,
    HUMAN_QUALITIES,
    LUGGAGE,
    PHOBIAS,
    BUNKER,
    SPECIAL_CARD,
    HOBBY_GET_SPECIAL_CARD,
    HEALTH_GET_SPECIAL_CARD,
    EXTRA_SKILLS_GET_SPECIAL_CARD,
    HUMAN_QUALITIES_GET_SPECIAL_CARD,
    LUGGAGE_GET_SPECIAL_CARD,
    PHOBIAS_GET_SPECIAL_CARD,
}
